---
abstract: 'A plugin for writing RESTful apps with Dancer2'
author:
  - 'Dancer Core Developers'
build_requires:
  Dancer2::Core::Request: '0'
  Dancer2::Test: '0'
  Data::Dumper: '0'
  File::Spec: '0'
  HTTP::Request::Common: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  JSON: '0'
  Module::Build: '0.3601'
  Module::Runtime: '0'
  Plack::Test: '0'
  Test::More: '0.88'
  perl: '5.006'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer2-Plugin-REST
provides:
  Dancer2::Plugin::REST:
    file: lib/Dancer2/Plugin/REST.pm
    version: '0.22'
requires:
  Carp: '0'
  Class::Load: '0'
  Dancer2: '0.140001'
  Dancer2::Plugin: '0'
  Moo::Role: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/perldancer/Dancer2-Plugin-REST/issues
  homepage: http://search.cpan.org/dist/Dancer2-Plugin-REST/
  repository: https://github.com/perldancer/Dancer2-Plugin-REST.git
version: '0.22'
x_authority: cpan:SUKRIA
