---
abstract: 'REST plugin for Dancer'
author:
  - unknown
build_requires:
  Test::More: 0.87
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer2-Plugin-REST
no_index:
  directory:
    - t
    - inc
requires:
  Dancer2: 0
  JSON: 0
resources:
  repository: http://github.com/yanick/Dancer2-Plugin-REST
version: 0.08
