---
abstract: 'A plugin for writing RESTful apps with Dancer2'
author:
  - 'Dancer Core Developers'
build_requires:
  Class::Load: 0
  Dancer2::Core::Request: 0
  Dancer2::Test: 0
  ExtUtils::MakeMaker: 0
  File::Spec: 0
  File::Spec::Functions: 0
  IO::Handle: 0
  IPC::Open3: 0
  JSON: 0
  List::Util: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300037, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer2-Plugin-REST
provides:
  Dancer2::Plugin::REST:
    file: lib/Dancer2/Plugin/REST.pm
    version: 0.13
requires:
  Carp: 0
  Dancer2: 0
  Dancer2::Plugin: 0
  Moo::Role: 0
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/yanick/Dancer2-Plugin-REST
  repository: https://github.com/yanick/Dancer2-Plugin-REST.git
version: 0.13
x_authority: cpan:SUKRIA
